name = "xox"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"
[build.environment]
NODE_VERSION = "18.17.1"

[site]
bucket = "./out"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
dir = ".next/server"