name = "tic-tac-toe-game"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = ".next"

[env.production]
NEXT_PUBLIC_SOCKET_URL = "https://twoja-domena.com"

[[routes]]
pattern = "/api/socket"
script = "api/server.js"